sudo: required
language: python
python: "3.8"

addons:
  postgresql: "9.6"

before_install:
  - cd ${TRAVIS_BUILD_DIR}
  - nvm install 16

install:
  - npm install
  - pip3 install tox

script:
  - pip3 install -r requirements.txt
  - tox --parallel || travis_terminate 1
